export const AGREE = 'AGREE'
export const DISAGREE = 'DISAGREE'
export const REFUSE = 'REFUSE'
export const UPDATE_CONTENT = 'UPDATE_CONTENT'
export const FETCH_DATA = 'FETCH_DATA'
export const SET_ACTIVE = 'SET_ACTIVE'
export const FETCH_DECISIONS = 'FETCH_DECISIONS'
